name: Generate and Sign SBOM

on:
  push:
    branches: [main, add-sbom-workflow]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  COMPONENT_VERSION: ${{ github.sha }}

jobs:
  sbom:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM with Syft
        uses: anchore/sbom-action@v0.20.6
        with:
          path: ./marketing/
